docker-compose.yml

version: '2'
services:
  mongodb-datavolume:
    image: busybox
    stdin_open: true
    entrypoint:
    - /bin/true
    network_mode: none
    volumes:
    - /media/data1/mongodbWithVolume2/mongodb/db:/data/db
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
  mongodb:
    image: mongo
    stdin_open: true
    tty: true
    volumes_from:
    - mongodb-datavolume
    command:
    - --replSet
    - replica_set
    labels:
      io.rancher.sidekicks: mongodb-datavolume
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/mongodb



rancher-compose.yml

version: '2'
services:
  mongodb-datavolume:
    scale: 3
    start_on_create: true
  mongodb:
    scale: 3
    start_on_create: true